-- 저자 별 카테고리 별 매출액 집계하기
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES FROM BOOK_SALES AS S
JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY CATEGORY, AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC
-- total sales = 판매량 * 판매가
-- join으로 묶어서 년도랑 월로 가르기
