--카테고리 별 도서 판매량 집계하기
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES 
FROM BOOK AS B
JOIN BOOK_SALES AS S 
ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC
-- sum으로 토탈 합 만들고 나머지는 다른거랑 유사