--성분으로 구분한 아이스크림 총 주문량
SELECT I.INGREDIENT_TYPE , SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO AS I
JOIN FIRST_HALF AS F WHERE F.FLAVOR = I.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER
