--대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE>= '2022-08-01' AND START_DATE <= '2022-10-31'AND CAR_ID 
IN(SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
   WHERE START_DATE>= '2022-08-01' AND START_DATE <= '2022-10-31' 
   GROUP BY CAR_ID 
   HAVING COUNT(HISTORY_ID)>=5)
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC
-- IN 안으로 조건 새로 달아주고 group by, having으로 조건 더해주기
