-- 과일로 만든 아이스크림 고르기
SELECT F.FLAVOR FROM FIRST_HALF AS F
JOIN ICECREAM_INFO AS I
ON F.FLAVOR = I.FLAVOR
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = 'fruit_based'
-- TOTAL_ORDER>3000, INGREdiENT_TYPE = fruit_based
-- inner join 활용 