--오프라인/온라인 판매 데이터 통합하기
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE ,PRODUCT_ID,USER_ID,SALES_AMOUNT FROM ONLINE_SALE AS A
WHERE SALES_DATE LIKE '2022-03%'
UNION
SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE ,PRODUCT_ID,NULL AS USER_ID,SALES_AMOUNT FROM OFFLINE_SALE AS B
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE,PRODUCT_ID, USER_ID

-- join과 union의 차이
-- inner join = 교집합. 둘다 지정. outer join = 합집합 cross join = 곱집합 union = select 여러개. 각각마다 조건 달릴때