-- 서울에 위치한 식당 목록 조회하기
SELECT R.REST_ID,I.REST_NAME,I.FOOD_TYPE,I.FAVORITES,I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE),2) AS SCORE FROM REST_INFO AS I
JOIN REST_REVIEW AS R ON I.REST_ID = R.REST_ID
GROUP BY R.REST_ID
HAVING I.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC

--INFO 기준으로 조인, round로 소수점 셋째자리 반올림, as로 이름 변경, having like로 그룹 조건, 둘다 desc